This competition is evaluated on the mean Dice coefficient. The Dice coefficient can be used to compare the pixel-wise agreement between a predicted segmentation and its corresponding ground truth. The formula is given by:

$$\frac{2 \cdot |X \cap Y|}{|X| + |Y|},$$

where X is the predicted set of pixels and Y is the ground truth. The Dice coefficient is defined to be 1 when both X and Y are empty. The leaderboard score is the mean of the Dice coefficients for each image in the test set.

In order to reduce the submission file size, our metric uses run-length encoding on the pixel values.  Instead of submitting an exhaustive list of indices for your segmentation, you will submit pairs of values that contain a start position and a run length. E.g. '1 3' implies starting at pixel 1 and running a total of 3 pixels (1,2,3).

The competition format requires a space delimited list of pairs. For example, '1 3 10 5' implies pixels 1,2,3,10,11,12,13,14 are to be included in the mask. The metric checks that the pairs are sorted, positive, and the decoded pixel values are not duplicated. The pixels are numbered from top to bottom, then left to right: 1 is pixel (1,1), 2 is pixel (2,1), etc.

### $$type(x) = type(y) = class 'numpy.ndarray'$$
### $$x.shape = y.shape = (420, 580) | (105, 145)$$

In [4]:
import numpy as np
def dice_coefficient(x, y):
    if not(x.any() or y.any()):
        return 1
    return 2 * (x.astype(bool) * y.astype(bool)).sum() / (x.sum() + y.sum())

In [16]:
x = np.array([[1, 1], [1, 0]])
y = np.array([[1, 0], [1, 0]])

In [17]:
print("x: ", '|x| = ', x.sum())
print(x)
print("y: ", '|y| = ', y.sum())
print(y)
z = x.astype(bool) * y.astype(bool)
print("z: ", '|z| = ', z.sum())
print(z.astype(int))
dice_coefficient(x, y)

x:  |x| =  3
[[1 1]
 [1 0]]
y:  |y| =  2
[[1 0]
 [1 0]]
z:  |z| =  2
[[1 0]
 [1 0]]


0.80000000000000004